apiVersion: v1
kind: Pod
metadata:
   name: dynamic-agents
   labels:
      app: dynamic-agents
spec:
  containers:
  - name: maven
    image: maven:3.8.3-adoptopenjdk-11
    command:
    - cat 
    tty: true
